services:
  mysql:
    image: mysql:8.0
    container_name: real_estate_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: user_mydb
      MYSQL_PASSWORD: rootPASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/ddl-properties.sql:/docker-entrypoint-initdb.d/ddl-properties.sql

volumes:
  mysql_data: